# ==========================================================
# AI Resume Screening Agent
# SQLite Database Configuration
# ==========================================================

# ----------------------------------------------------------
# Import Required Libraries
# ----------------------------------------------------------

import sqlite3
import os

# ----------------------------------------------------------
# Database Name
# ----------------------------------------------------------

DATABASE_NAME = "resume_screening.db"

# ----------------------------------------------------------
# Database Connection Function
# ----------------------------------------------------------

def get_connection():
    """
    Create and return a connection to the SQLite database.

    Returns:
        sqlite3.Connection:
            Active database connection object.
    """

    database_path = os.path.abspath(DATABASE_NAME)

    print("========== DATABASE PATH ==========")
    print(database_path)
    print("Current Working Directory:", os.getcwd())

    connection = sqlite3.connect(database_path)

    return connection


# ----------------------------------------------------------
# Create Candidate Table
# ----------------------------------------------------------

def create_database():
    """
    Create the Candidate table if it does not already exist.

    This function is safe to execute every time the application
    starts because SQLite ignores the CREATE TABLE statement
    when the table already exists.
    """

    connection = get_connection()

    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS candidates (

            id INTEGER PRIMARY KEY AUTOINCREMENT,

            name TEXT NOT NULL,

            email TEXT,

            phone TEXT,

            education TEXT,

            experience INTEGER,

            skills TEXT,

            certifications TEXT,

            prediction TEXT,

            confidence REAL,

            match_score INTEGER,

            recommendation TEXT,

            status TEXT DEFAULT 'Pending',

            uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

        )
    """)

    connection.commit()

    connection.close()


# ----------------------------------------------------------
# Initialize Database
# ----------------------------------------------------------

create_database()

# ==========================================================
# Insert Candidate Record
# ==========================================================

def insert_candidate(
    parsed_resume,
    prediction,
    confidence,
    match_score,
    recommendation
):
    """
    Insert a screened candidate into the SQLite database.

    Parameters
    ----------
    parsed_resume : dict
        Parsed candidate information returned by resume_parser.py

    prediction : str
        ML prediction (Selected / Rejected)

    confidence : float or str
        Prediction confidence.

    match_score : int
        AI Resume Match Score.

    recommendation : str
        HR Recommendation generated by AI.
    """

    # ------------------------------------------------------
    # Create Database Connection
    # ------------------------------------------------------

    connection = get_connection()

    cursor = connection.cursor()

    # ------------------------------------------------------
    # Convert Lists to Strings
    # ------------------------------------------------------

    skills = ", ".join(parsed_resume.get("Skills", []))

    certifications = ", ".join(
        parsed_resume.get("Certifications", [])
    )

    # ------------------------------------------------------
    # Convert Confidence to Numeric Value
    # ------------------------------------------------------

    if isinstance(confidence, str):

        confidence = confidence.replace("%", "")

    try:

        confidence = float(confidence)

    except Exception:

        confidence = 0.0

    # ------------------------------------------------------
    # Insert Candidate Record
    # ------------------------------------------------------
    print("========== INSERT CANDIDATE ==========")
    print(parsed_resume)
    print(prediction)
    print(confidence)
    print(match_score)
    print(recommendation)
    cursor.execute("""

        INSERT INTO candidates (

            name,
            email,
            phone,
            education,
            experience,
            skills,
            certifications,
            prediction,
            confidence,
            match_score,
            recommendation

        )

        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

    """, (

        parsed_resume.get("Name", ""),

        parsed_resume.get("Email", ""),

        parsed_resume.get("Phone", ""),

        parsed_resume.get("Education", ""),

        parsed_resume.get("Experience", 0),

        skills,

        certifications,

        prediction,

        confidence,

        match_score,

        recommendation

    ))

    # ------------------------------------------------------
    # Save Changes
    # ------------------------------------------------------

    connection.commit()

    connection.close()

    # ------------------------------------------------------
    # Return Success Message
    # ------------------------------------------------------

    return {

        "Status": "Success",

        "Message": "Candidate saved successfully."

    }

# ==========================================================
# Get All Candidates
# ==========================================================

def get_all_candidates():
    """
    Retrieve all candidate records from the SQLite database.

    Returns
    -------
    list[dict]
        A list of dictionaries, where each dictionary
        represents a candidate record.
    """

    # ------------------------------------------------------
    # Create Database Connection
    # ------------------------------------------------------

    connection = get_connection()

    # ------------------------------------------------------
    # Return Rows as Dictionaries
    # ------------------------------------------------------

    connection.row_factory = sqlite3.Row

    cursor = connection.cursor()

    # ------------------------------------------------------
    # Retrieve All Candidate Records
    # ------------------------------------------------------

    cursor.execute("""

        SELECT *

        FROM candidates

        ORDER BY uploaded_at DESC

    """)

    rows = cursor.fetchall()

    # ------------------------------------------------------
    # Convert Rows to Dictionary List
    # ------------------------------------------------------

    candidates = []

    for row in rows:

        candidates.append(dict(row))

    # ------------------------------------------------------
    # Close Database Connection
    # ------------------------------------------------------

    connection.close()

    # ------------------------------------------------------
    # Return Candidate List
    # ------------------------------------------------------

    return candidates

# ==========================================================
# Get Candidate by ID
# ==========================================================

def get_candidate(candidate_id):
    """
    Retrieve a single candidate from the SQLite database
    using the candidate's unique ID.

    Parameters
    ----------
    candidate_id : int
        Unique candidate ID.

    Returns
    -------
    dict | None
        Candidate information if found,
        otherwise None.
    """

    # ------------------------------------------------------
    # Create Database Connection
    # ------------------------------------------------------

    connection = get_connection()

    # ------------------------------------------------------
    # Return Rows as Dictionaries
    # ------------------------------------------------------

    connection.row_factory = sqlite3.Row

    cursor = connection.cursor()

    # ------------------------------------------------------
    # Retrieve Candidate
    # ------------------------------------------------------

    cursor.execute("""

        SELECT *

        FROM candidates

        WHERE id = ?

    """, (candidate_id,))

    row = cursor.fetchone()

    # ------------------------------------------------------
    # Close Database Connection
    # ------------------------------------------------------

    connection.close()

    # ------------------------------------------------------
    # Return Candidate
    # ------------------------------------------------------

    if row is None:

        return None

    return dict(row)

# ==========================================================
# Update Candidate Status
# ==========================================================

def update_candidate_status(candidate_id, status):
    """
    Update the recruitment status of a candidate.

    Parameters
    ----------
    candidate_id : int
        Unique candidate ID.

    status : str
        New recruitment status.

        Example:
            Pending
            Shortlisted
            Rejected
            Hired

    Returns
    -------
    dict
        Status message indicating whether the update
        was successful.
    """

    # ------------------------------------------------------
    # Create Database Connection
    # ------------------------------------------------------

    connection = get_connection()

    cursor = connection.cursor()

    # ------------------------------------------------------
    # Update Candidate Status
    # ------------------------------------------------------

    cursor.execute("""

        UPDATE candidates

        SET status = ?

        WHERE id = ?

    """, (

        status,

        candidate_id

    ))

    # ------------------------------------------------------
    # Save Changes
    # ------------------------------------------------------

    connection.commit()

    # ------------------------------------------------------
    # Check Whether Record Exists
    # ------------------------------------------------------

    if cursor.rowcount == 0:

        connection.close()

        return {

            "Status": "Failed",

            "Message": "Candidate not found."

        }

    # ------------------------------------------------------
    # Close Connection
    # ------------------------------------------------------

    connection.close()

    # ------------------------------------------------------
    # Return Success
    # ------------------------------------------------------

    return {

        "Status": "Success",

        "Message": "Candidate status updated successfully."

    }

# ==========================================================
# Delete Candidate
# ==========================================================

def delete_candidate(candidate_id):
    """
    Delete a candidate record from the SQLite database.

    Parameters
    ----------
    candidate_id : int
        Unique ID of the candidate.

    Returns
    -------
    dict
        Status message indicating whether the deletion
        was successful.
    """

    # ------------------------------------------------------
    # Create Database Connection
    # ------------------------------------------------------

    connection = get_connection()

    cursor = connection.cursor()

    # ------------------------------------------------------
    # Delete Candidate Record
    # ------------------------------------------------------

    cursor.execute("""

        DELETE FROM candidates

        WHERE id = ?

    """, (

        candidate_id,

    ))

    # ------------------------------------------------------
    # Save Changes
    # ------------------------------------------------------

    connection.commit()

    # ------------------------------------------------------
    # Check Whether Candidate Exists
    # ------------------------------------------------------

    if cursor.rowcount == 0:

        connection.close()

        return {

            "Status": "Failed",

            "Message": "Candidate not found."

        }

    # ------------------------------------------------------
    # Close Database Connection
    # ------------------------------------------------------

    connection.close()

    # ------------------------------------------------------
    # Return Success Message
    # ------------------------------------------------------

    return {

        "Status": "Success",

        "Message": "Candidate deleted successfully."

    }
